### ISSUE TITLE
An error message occurs on the latest Bagnon after logging in.

### ISSUE THREAD

**Issue by chkmyid** [AzeriteTeam/Bagnon_ItemLevel#2]
```
2x Bagnon_ItemLevel\main.lua:210: Usage: hooksecurefunc([table,] "function", hookfunc)
[C]: in function `hooksecurefunc'
Bagnon_ItemLevel\main.lua:210: in function `?'
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:20: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0-1.lua:56: in function <...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[C]: ?
...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: in function `LoadAddOn'
Skillet-Classic\Skillet-11302.nil.lua:131: in function `DisableBlizzardFrame'
Skillet-Classic\Skillet-11302.nil.lua:652: in function <Skillet-Classic\Skillet.lua:568>
[C]: ?
…faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <…faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
…faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
…faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <…faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:353: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:424: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:693: in function <FrameXML\UIParent.lua:658>
```

**Comment by goldpaw** [comment]
The latest bagnon release version was 8.2.16 on October 5th. The lastest version is tagged as beta version, so I'm holding back any fixes from my end until I see an actual release version. I've seen beta bugs been fixed before making it to release before.

**Comment by chkmyid** [comment]
lastest version is 8.2.17 on December 4th.
[Bagnon](https://www.curseforge.com/wow/addons/bagnon/files/all)

I have to delete this addon until a stable version of Bagnon is available. I don't think it's a good idea to leave this addon with an error, waiting for the release version to come at any time.

**Comment by goldpaw** [comment]
![Screenshot from 2019-12-05 10-16-06](https://user-images.githubusercontent.com/6476535/70221297-5fc43600-1748-11ea-9cd0-b61a712535ef.png)

8.2.17 is tagged as a beta version, not release. Thus it is only downloaded by those who specifically (and manually) have chosen to download beta versions of Bagnon, risk more bugs, incompatibilities etc. This is not the version that the majority are using. 

I'll relate to this if it turns out to be an intentional API change in bagnon that makes it to the final release versions.

**Comment by chkmyid** [comment]
The release version has been released, but it still does not work.

**Comment by goldpaw** [comment]
Yeah. They changed something in their back-end and it's affecting pretty much all our bagnon plugins. I'll take a look at it.

**Comment by bryansray** [comment]
So it looks like `Bagnon.ItemSlot` is `nil` when the `Module:OnEnable` function is called. My hunch is that it isn't intended to be nil? I'm trying to track down what it was before the bug was introduced.

**Comment by bryansray** [comment]
Okay so it looks like [this commit](https://github.com/tullamods/Bagnon/commit/7774486d6f6ac8c1fcf72ed84d4520688f3fc1ea) removed changed `ItemSlot` to `Item` ... this brings the error count from 3 down to 2, but now there are a couple other bugs to track down.

**Comment by bryansray** [comment]
@goldpaw I put in a PR to resolve this issue. Hope it helps. 👍

**Comment by goldpaw** [comment]
Fixed
